name: AppyKids
favicon: null
layout_spectrum: 0.06647510663606226
typography_spectrum: 0.565522194141522
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7881533165927976
  lightness: 0.9673023554496467
  saturation: 0.7002328801900148
  rhythmicContrast: 0.4962934192735702
purpose: []
