name: AppyKids
favicon: null
layout_spectrum: 0.24288
typography_spectrum: 0.1412
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#450a10'
    - '#ffffff'
    - '#436679'
    - '#f3bc23'
    - '#f04e97'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
